services:
  bot:
    build: .
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/wildberries_bot
      - REDIS_URL=redis://redis:6379
      - WB_API_URL=http://mock:8000/api
      - TELEGRAM_BOT_TOKEN=7081696323:AAHMME68JTKvSFFDkzFDjIm1G0qBIxfpAQw
    depends_on:
      - db
      - redis
      - mock
    volumes:
      - .:/app

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wildberries_bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  mock:
    build:
      context: .
      dockerfile: Dockerfile.mock
    ports:
      - "8002:8000"

volumes:
  postgres_data: